#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : libsigc++
Version  : 3.6.0
Release  : 23
URL      : https://download.gnome.org/sources/libsigc++/3.6/libsigc++-3.6.0.tar.xz
Source0  : https://download.gnome.org/sources/libsigc++/3.6/libsigc++-3.6.0.tar.xz
Summary  : Typesafe signal and callback system for C++
Group    : Development/Tools
License  : LGPL-3.0
Requires: libsigc++-lib = %{version}-%{release}
Requires: libsigc++-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : mm-common-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory contains files not tracked by a source code control program,
The files can have one of two origins.

%package dev
Summary: dev components for the libsigc++ package.
Group: Development
Requires: libsigc++-lib = %{version}-%{release}
Provides: libsigc++-devel = %{version}-%{release}
Requires: libsigc++ = %{version}-%{release}

%description dev
dev components for the libsigc++ package.


%package lib
Summary: lib components for the libsigc++ package.
Group: Libraries
Requires: libsigc++-license = %{version}-%{release}

%description lib
lib components for the libsigc++ package.


%package license
Summary: license components for the libsigc++ package.
Group: Default

%description license
license components for the libsigc++ package.


%prep
%setup -q -n libsigc++-3.6.0
cd %{_builddir}/libsigc++-3.6.0
pushd ..
cp -a libsigc++-3.6.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1696256719
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/libsigc++
cp %{_builddir}/libsigc++-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libsigc++/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c || :
cp %{_builddir}/libsigc++-%{version}/docs/license.md %{buildroot}/usr/share/package-licenses/libsigc++/ef18bc4aa7f357a00c16d0dce2a81ca2a08b32ac || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
## install_append content
rm -f %{buildroot}/usr/share/doc/libsigc++-*/reference/html/structsigc_1_1type__trait_3_01T__type*

## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/sigc++-3.0/sigc++/adaptors/adaptor_base.h
/usr/include/sigc++-3.0/sigc++/adaptors/adaptor_trait.h
/usr/include/sigc++-3.0/sigc++/adaptors/adaptors.h
/usr/include/sigc++-3.0/sigc++/adaptors/adapts.h
/usr/include/sigc++-3.0/sigc++/adaptors/bind.h
/usr/include/sigc++-3.0/sigc++/adaptors/bind_return.h
/usr/include/sigc++-3.0/sigc++/adaptors/bound_argument.h
/usr/include/sigc++-3.0/sigc++/adaptors/compose.h
/usr/include/sigc++-3.0/sigc++/adaptors/exception_catch.h
/usr/include/sigc++-3.0/sigc++/adaptors/hide.h
/usr/include/sigc++-3.0/sigc++/adaptors/retype.h
/usr/include/sigc++-3.0/sigc++/adaptors/retype_return.h
/usr/include/sigc++-3.0/sigc++/adaptors/track_obj.h
/usr/include/sigc++-3.0/sigc++/adaptors/tuple_visitor_visit_each.h
/usr/include/sigc++-3.0/sigc++/bind.h
/usr/include/sigc++-3.0/sigc++/bind_return.h
/usr/include/sigc++-3.0/sigc++/connection.h
/usr/include/sigc++-3.0/sigc++/functors/functor_trait.h
/usr/include/sigc++-3.0/sigc++/functors/functors.h
/usr/include/sigc++-3.0/sigc++/functors/mem_fun.h
/usr/include/sigc++-3.0/sigc++/functors/ptr_fun.h
/usr/include/sigc++-3.0/sigc++/functors/slot.h
/usr/include/sigc++-3.0/sigc++/functors/slot_base.h
/usr/include/sigc++-3.0/sigc++/limit_reference.h
/usr/include/sigc++-3.0/sigc++/member_method_trait.h
/usr/include/sigc++-3.0/sigc++/reference_wrapper.h
/usr/include/sigc++-3.0/sigc++/retype_return.h
/usr/include/sigc++-3.0/sigc++/scoped_connection.h
/usr/include/sigc++-3.0/sigc++/sigc++.h
/usr/include/sigc++-3.0/sigc++/signal.h
/usr/include/sigc++-3.0/sigc++/signal_base.h
/usr/include/sigc++-3.0/sigc++/slot.h
/usr/include/sigc++-3.0/sigc++/trackable.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_cdr.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_end.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_for_each.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_start.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_transform_each.h
/usr/include/sigc++-3.0/sigc++/type_traits.h
/usr/include/sigc++-3.0/sigc++/visit_each.h
/usr/include/sigc++-3.0/sigc++/weak_raw_ptr.h
/usr/lib64/libsigc-3.0.so
/usr/lib64/pkgconfig/sigc++-3.0.pc
/usr/lib64/sigc++-3.0/include/sigc++config.h

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libsigc-3.0.so.0.0.0
/usr/lib64/libsigc-3.0.so.0
/usr/lib64/libsigc-3.0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsigc++/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c
/usr/share/package-licenses/libsigc++/ef18bc4aa7f357a00c16d0dce2a81ca2a08b32ac
